apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-threatgen-prod

resources:
  - ../../base

images:
  - name: tsg
    newName: image-registry.openshift-image-registry.svc:5000/ai-threatgen-ci/tsg
    newTag: latest

patches:
  - path: configmap-patch.yaml
  - path: replicas-patch.yaml
